# Generated by Django 4.0.5 on 2022-06-20 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tracks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1024)),
                ('artist', models.CharField(max_length=1024)),
                ('duration', models.IntegerField()),
                ('last_play', models.DateTimeField()),
            ],
        ),
    ]
